// <auto-generated />
using Comandas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comandas.Migrations
{
    [DbContext(typeof(ComandasContext))]
    partial class ComandasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Cadeiras.Cadeiras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cadeiras");
                });

            modelBuilder.Entity("Models.Mesas.Mesas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CadeirasId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CadeirasId");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("Models.Reservas.Reservas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Numero_MesaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Numero_MesaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Models.Mesas.Mesas", b =>
                {
                    b.HasOne("Models.Cadeiras.Cadeiras", "Cadeiras")
                        .WithMany()
                        .HasForeignKey("CadeirasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadeiras");
                });

            modelBuilder.Entity("Models.Reservas.Reservas", b =>
                {
                    b.HasOne("Models.Mesas.Mesas", "Numero_Mesa")
                        .WithMany()
                        .HasForeignKey("Numero_MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Numero_Mesa");
                });
#pragma warning restore 612, 618
        }
    }
}
